runtime: nodejs20

env_variables:
  MONGO_URI: "mongodb+srv://joinCourse90:qwertyStuff@cluster0.okwj5.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0"
  ACCESS_TOKEN_SECRET: "9ca2d98b53625bdce57236bbdd11d4e324a8156820bc801e5df17bdbcd913bed9b2f8fb614a339f5a91f6d6b32e9dd2e3d9712511ab377bdad99b2bee8961ccd"
  PORT: "8080"
  RAZORPAY_KEY_ID: "rzp_test_U2VtJuCBm6k69C"
  RAZORPAY_KEY_SECRET: "RwIYrCSGNdbGwsPaYqB2ViNZ"
  merchant_account_id: "EHG1ptFx8L4eLK"
  NODE_ENV: "production"
  # Add other environment variables

instance_class: F1 # Free tier

automatic_scaling:
  target_cpu_utilization: 0.65
  min_instances: 1
  max_instances: 10
  target_throughput_utilization: 0.6

handlers:
  - url: /.*
    script: auto
    secure: always

env: standard
